#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbventasProyectTer")]
	public partial class LoginDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LoginDataContext() : 
				base(global::CapaPresentacion.Properties.Settings.Default.dbventasProyectTerConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LoginDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LoginDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LoginDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LoginDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.accesologin")]
		public ISingleResult<accesologinResult> accesologin([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, password);
			return ((ISingleResult<accesologinResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.estadoconexion")]
		public ISingleResult<estadoconexionResult> estadoconexion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cod_usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cod_usuario);
			return ((ISingleResult<estadoconexionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCerrarCesion")]
		public int spCerrarCesion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string strUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), strUsuario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spControlAcceso")]
		public int spControlAcceso([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string contraseña)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, contraseña);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spEstablecerTasa")]
		public ISingleResult<spEstablecerTasaResult> spEstablecerTasa()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spEstablecerTasaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spTasaActiva")]
		public ISingleResult<spTasaActivaResult> spTasaActiva()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spTasaActivaResult>)(result.ReturnValue));
		}
	}
	
	public partial class accesologinResult
	{
		
		private int _rolacceso;
		
		private string _usuario;
		
		private string _pass;
		
		private int _cod_usuario;
		
		public accesologinResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rolacceso", DbType="Int NOT NULL")]
		public int rolacceso
		{
			get
			{
				return this._rolacceso;
			}
			set
			{
				if ((this._rolacceso != value))
				{
					this._rolacceso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this._usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this._pass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_usuario", DbType="Int NOT NULL")]
		public int cod_usuario
		{
			get
			{
				return this._cod_usuario;
			}
			set
			{
				if ((this._cod_usuario != value))
				{
					this._cod_usuario = value;
				}
			}
		}
	}
	
	public partial class estadoconexionResult
	{
		
		private int _id_control_acceso;
		
		private int _usuario;
		
		private char _estadoacceso;
		
		private System.Nullable<System.DateTime> _dtConexion;
		
		private System.Nullable<System.DateTime> _dtDesconexion;
		
		public estadoconexionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_control_acceso", DbType="Int NOT NULL")]
		public int id_control_acceso
		{
			get
			{
				return this._id_control_acceso;
			}
			set
			{
				if ((this._id_control_acceso != value))
				{
					this._id_control_acceso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="Int NOT NULL")]
		public int usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this._usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estadoacceso", DbType="Char(1) NOT NULL")]
		public char estadoacceso
		{
			get
			{
				return this._estadoacceso;
			}
			set
			{
				if ((this._estadoacceso != value))
				{
					this._estadoacceso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtConexion", DbType="DateTime")]
		public System.Nullable<System.DateTime> dtConexion
		{
			get
			{
				return this._dtConexion;
			}
			set
			{
				if ((this._dtConexion != value))
				{
					this._dtConexion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtDesconexion", DbType="DateTime")]
		public System.Nullable<System.DateTime> dtDesconexion
		{
			get
			{
				return this._dtDesconexion;
			}
			set
			{
				if ((this._dtDesconexion != value))
				{
					this._dtDesconexion = value;
				}
			}
		}
	}
	
	public partial class spEstablecerTasaResult
	{
		
		private double _flValorCambio;
		
		public spEstablecerTasaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flValorCambio", DbType="Float NOT NULL")]
		public double flValorCambio
		{
			get
			{
				return this._flValorCambio;
			}
			set
			{
				if ((this._flValorCambio != value))
				{
					this._flValorCambio = value;
				}
			}
		}
	}
	
	public partial class spTasaActivaResult
	{
		
		private int _ID;
		
		private System.DateTime _Fecha_de_Vigencia;
		
		private double _Valor_C__por__;
		
		private System.Nullable<System.DateTime> _Registrado;
		
		public spTasaActivaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha de Vigencia]", Storage="_Fecha_de_Vigencia", DbType="Date NOT NULL")]
		public System.DateTime Fecha_de_Vigencia
		{
			get
			{
				return this._Fecha_de_Vigencia;
			}
			set
			{
				if ((this._Fecha_de_Vigencia != value))
				{
					this._Fecha_de_Vigencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Valor C$ por $]", Storage="_Valor_C__por__", DbType="Float NOT NULL")]
		public double Valor_C__por__
		{
			get
			{
				return this._Valor_C__por__;
			}
			set
			{
				if ((this._Valor_C__por__ != value))
				{
					this._Valor_C__por__ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Registrado", DbType="DateTime")]
		public System.Nullable<System.DateTime> Registrado
		{
			get
			{
				return this._Registrado;
			}
			set
			{
				if ((this._Registrado != value))
				{
					this._Registrado = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
