#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Administracion
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbventasProyectTer")]
	public partial class DataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataDataContext() : 
				base(global::CapaDatos.Properties.Settings.Default.Con, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCambiarCredenciales")]
		public int spCambiarCredenciales([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string strUsuarioA, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string strUsuarioN, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string strContraseñaA, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string strContraseñaN, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(80)")] ref string mensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), strUsuarioA, strUsuarioN, strContraseñaA, strContraseñaN, mensaje);
			mensaje = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
