#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.Administración
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbventasProyectTer")]
	public partial class DataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataDataContext() : 
				base(global::CapaPresentacion.Properties.Settings.Default.dbventasProyectTerConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spBuscarConexion")]
		public ISingleResult<spBuscarConexionResult> spBuscarConexion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> filtro)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, filtro);
			return ((ISingleResult<spBuscarConexionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spMostrarHistorialAcceso")]
		public ISingleResult<spMostrarHistorialAccesoResult> spMostrarHistorialAcceso()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spMostrarHistorialAccesoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spMostrarHistorialBloqueado")]
		public ISingleResult<spMostrarHistorialBloqueadoResult> spMostrarHistorialBloqueado()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spMostrarHistorialBloqueadoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spMostrarHistorialConectado")]
		public ISingleResult<spMostrarHistorialConectadoResult> spMostrarHistorialConectado()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spMostrarHistorialConectadoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spMostrarHistorialDesconectado")]
		public ISingleResult<spMostrarHistorialDesconectadoResult> spMostrarHistorialDesconectado()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spMostrarHistorialDesconectadoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spBuscarTasa")]
		public ISingleResult<spBuscarTasaResult> spBuscarTasa([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fecha);
			return ((ISingleResult<spBuscarTasaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spTasaActiva")]
		public ISingleResult<spTasaActivaResult> spTasaActiva()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spTasaActivaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDefinirTasa")]
		public int spDefinirTasa([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] ref System.Nullable<double> tasa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tasa);
			tasa = ((System.Nullable<double>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class spBuscarConexionResult
	{
		
		private int _ID_Conexion;
		
		private int _CodUsuario;
		
		private string _Usuario;
		
		private char _Estado_Conexión;
		
		private System.Nullable<System.DateTime> _Conectado;
		
		private System.Nullable<System.DateTime> _Desconectado;
		
		public spBuscarConexionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ID Conexion]", Storage="_ID_Conexion", DbType="Int NOT NULL")]
		public int ID_Conexion
		{
			get
			{
				return this._ID_Conexion;
			}
			set
			{
				if ((this._ID_Conexion != value))
				{
					this._ID_Conexion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodUsuario", DbType="Int NOT NULL")]
		public int CodUsuario
		{
			get
			{
				return this._CodUsuario;
			}
			set
			{
				if ((this._CodUsuario != value))
				{
					this._CodUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Estado Conexión]", Storage="_Estado_Conexión", DbType="Char(1) NOT NULL")]
		public char Estado_Conexión
		{
			get
			{
				return this._Estado_Conexión;
			}
			set
			{
				if ((this._Estado_Conexión != value))
				{
					this._Estado_Conexión = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Conectado", DbType="DateTime")]
		public System.Nullable<System.DateTime> Conectado
		{
			get
			{
				return this._Conectado;
			}
			set
			{
				if ((this._Conectado != value))
				{
					this._Conectado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Desconectado", DbType="DateTime")]
		public System.Nullable<System.DateTime> Desconectado
		{
			get
			{
				return this._Desconectado;
			}
			set
			{
				if ((this._Desconectado != value))
				{
					this._Desconectado = value;
				}
			}
		}
	}
	
	public partial class spMostrarHistorialAccesoResult
	{
		
		private int _ID_Conexion;
		
		private int _CodUsuario;
		
		private string _Usuario;
		
		private char _Estado_Conexión;
		
		private System.Nullable<System.DateTime> _Conectado;
		
		private System.Nullable<System.DateTime> _Desconectado;
		
		public spMostrarHistorialAccesoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ID Conexion]", Storage="_ID_Conexion", DbType="Int NOT NULL")]
		public int ID_Conexion
		{
			get
			{
				return this._ID_Conexion;
			}
			set
			{
				if ((this._ID_Conexion != value))
				{
					this._ID_Conexion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodUsuario", DbType="Int NOT NULL")]
		public int CodUsuario
		{
			get
			{
				return this._CodUsuario;
			}
			set
			{
				if ((this._CodUsuario != value))
				{
					this._CodUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Estado Conexión]", Storage="_Estado_Conexión", DbType="Char(1) NOT NULL")]
		public char Estado_Conexión
		{
			get
			{
				return this._Estado_Conexión;
			}
			set
			{
				if ((this._Estado_Conexión != value))
				{
					this._Estado_Conexión = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Conectado", DbType="DateTime")]
		public System.Nullable<System.DateTime> Conectado
		{
			get
			{
				return this._Conectado;
			}
			set
			{
				if ((this._Conectado != value))
				{
					this._Conectado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Desconectado", DbType="DateTime")]
		public System.Nullable<System.DateTime> Desconectado
		{
			get
			{
				return this._Desconectado;
			}
			set
			{
				if ((this._Desconectado != value))
				{
					this._Desconectado = value;
				}
			}
		}
	}
	
	public partial class spMostrarHistorialBloqueadoResult
	{
		
		private int _ID_Conexion;
		
		private int _CodUsuario;
		
		private string _Usuario;
		
		private char _Estado_Conexión;
		
		private System.Nullable<System.DateTime> _Conectado;
		
		private System.Nullable<System.DateTime> _Desconectado;
		
		public spMostrarHistorialBloqueadoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ID Conexion]", Storage="_ID_Conexion", DbType="Int NOT NULL")]
		public int ID_Conexion
		{
			get
			{
				return this._ID_Conexion;
			}
			set
			{
				if ((this._ID_Conexion != value))
				{
					this._ID_Conexion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodUsuario", DbType="Int NOT NULL")]
		public int CodUsuario
		{
			get
			{
				return this._CodUsuario;
			}
			set
			{
				if ((this._CodUsuario != value))
				{
					this._CodUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Estado Conexión]", Storage="_Estado_Conexión", DbType="Char(1) NOT NULL")]
		public char Estado_Conexión
		{
			get
			{
				return this._Estado_Conexión;
			}
			set
			{
				if ((this._Estado_Conexión != value))
				{
					this._Estado_Conexión = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Conectado", DbType="DateTime")]
		public System.Nullable<System.DateTime> Conectado
		{
			get
			{
				return this._Conectado;
			}
			set
			{
				if ((this._Conectado != value))
				{
					this._Conectado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Desconectado", DbType="DateTime")]
		public System.Nullable<System.DateTime> Desconectado
		{
			get
			{
				return this._Desconectado;
			}
			set
			{
				if ((this._Desconectado != value))
				{
					this._Desconectado = value;
				}
			}
		}
	}
	
	public partial class spMostrarHistorialConectadoResult
	{
		
		private int _ID_Conexion;
		
		private int _CodUsuario;
		
		private string _Usuario;
		
		private char _Estado_Conexión;
		
		private System.Nullable<System.DateTime> _Conectado;
		
		private System.Nullable<System.DateTime> _Desconectado;
		
		public spMostrarHistorialConectadoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ID Conexion]", Storage="_ID_Conexion", DbType="Int NOT NULL")]
		public int ID_Conexion
		{
			get
			{
				return this._ID_Conexion;
			}
			set
			{
				if ((this._ID_Conexion != value))
				{
					this._ID_Conexion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodUsuario", DbType="Int NOT NULL")]
		public int CodUsuario
		{
			get
			{
				return this._CodUsuario;
			}
			set
			{
				if ((this._CodUsuario != value))
				{
					this._CodUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Estado Conexión]", Storage="_Estado_Conexión", DbType="Char(1) NOT NULL")]
		public char Estado_Conexión
		{
			get
			{
				return this._Estado_Conexión;
			}
			set
			{
				if ((this._Estado_Conexión != value))
				{
					this._Estado_Conexión = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Conectado", DbType="DateTime")]
		public System.Nullable<System.DateTime> Conectado
		{
			get
			{
				return this._Conectado;
			}
			set
			{
				if ((this._Conectado != value))
				{
					this._Conectado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Desconectado", DbType="DateTime")]
		public System.Nullable<System.DateTime> Desconectado
		{
			get
			{
				return this._Desconectado;
			}
			set
			{
				if ((this._Desconectado != value))
				{
					this._Desconectado = value;
				}
			}
		}
	}
	
	public partial class spMostrarHistorialDesconectadoResult
	{
		
		private int _ID_Conexion;
		
		private int _CodUsuario;
		
		private string _Usuario;
		
		private char _Estado_Conexión;
		
		private System.Nullable<System.DateTime> _Conectado;
		
		private System.Nullable<System.DateTime> _Desconectado;
		
		public spMostrarHistorialDesconectadoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ID Conexion]", Storage="_ID_Conexion", DbType="Int NOT NULL")]
		public int ID_Conexion
		{
			get
			{
				return this._ID_Conexion;
			}
			set
			{
				if ((this._ID_Conexion != value))
				{
					this._ID_Conexion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodUsuario", DbType="Int NOT NULL")]
		public int CodUsuario
		{
			get
			{
				return this._CodUsuario;
			}
			set
			{
				if ((this._CodUsuario != value))
				{
					this._CodUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Estado Conexión]", Storage="_Estado_Conexión", DbType="Char(1) NOT NULL")]
		public char Estado_Conexión
		{
			get
			{
				return this._Estado_Conexión;
			}
			set
			{
				if ((this._Estado_Conexión != value))
				{
					this._Estado_Conexión = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Conectado", DbType="DateTime")]
		public System.Nullable<System.DateTime> Conectado
		{
			get
			{
				return this._Conectado;
			}
			set
			{
				if ((this._Conectado != value))
				{
					this._Conectado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Desconectado", DbType="DateTime")]
		public System.Nullable<System.DateTime> Desconectado
		{
			get
			{
				return this._Desconectado;
			}
			set
			{
				if ((this._Desconectado != value))
				{
					this._Desconectado = value;
				}
			}
		}
	}
	
	public partial class spBuscarTasaResult
	{
		
		private int _ID;
		
		private System.DateTime _Fecha_de_Vigencia;
		
		private double _Valor_C__por__;
		
		private System.Nullable<System.DateTime> _Registrado;
		
		public spBuscarTasaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha de Vigencia]", Storage="_Fecha_de_Vigencia", DbType="Date NOT NULL")]
		public System.DateTime Fecha_de_Vigencia
		{
			get
			{
				return this._Fecha_de_Vigencia;
			}
			set
			{
				if ((this._Fecha_de_Vigencia != value))
				{
					this._Fecha_de_Vigencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Valor C$ por $]", Storage="_Valor_C__por__", DbType="Float NOT NULL")]
		public double Valor_C__por__
		{
			get
			{
				return this._Valor_C__por__;
			}
			set
			{
				if ((this._Valor_C__por__ != value))
				{
					this._Valor_C__por__ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Registrado", DbType="DateTime")]
		public System.Nullable<System.DateTime> Registrado
		{
			get
			{
				return this._Registrado;
			}
			set
			{
				if ((this._Registrado != value))
				{
					this._Registrado = value;
				}
			}
		}
	}
	
	public partial class spTasaActivaResult
	{
		
		private int _ID;
		
		private System.DateTime _Fecha_de_Vigencia;
		
		private double _Valor_C__por__;
		
		private System.Nullable<System.DateTime> _Registrado;
		
		public spTasaActivaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha de Vigencia]", Storage="_Fecha_de_Vigencia", DbType="Date NOT NULL")]
		public System.DateTime Fecha_de_Vigencia
		{
			get
			{
				return this._Fecha_de_Vigencia;
			}
			set
			{
				if ((this._Fecha_de_Vigencia != value))
				{
					this._Fecha_de_Vigencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Valor C$ por $]", Storage="_Valor_C__por__", DbType="Float NOT NULL")]
		public double Valor_C__por__
		{
			get
			{
				return this._Valor_C__por__;
			}
			set
			{
				if ((this._Valor_C__por__ != value))
				{
					this._Valor_C__por__ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Registrado", DbType="DateTime")]
		public System.Nullable<System.DateTime> Registrado
		{
			get
			{
				return this._Registrado;
			}
			set
			{
				if ((this._Registrado != value))
				{
					this._Registrado = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
